### ISSUE TITLE
[FEATURE REQUEST] add autohash feature in webirc

### ISSUE THREAD

**Issue by T60Group** [realrasengan/jbnc#1]
add autohash feature in webirc so jbnc can pass a secure hash of a hostname/ip-address to a server for total anonymity
so instead of *!*@some-ip.ip-t.country.isp.com 
md5 of some-ip.ip-t.country.isp.com = 50f96456b50f5154835588baedce1581
sha256 is pretty long

**Comment by realrasengan** [comment]
Added.

https://github.com/realrasengan/jbnc/commit/4e7ce20207093275c1c1708c26a7729dce62758d
https://github.com/realrasengan/jbnc/commit/1cba8ff8904d9b86bfebb7de383d953dba138077
