### ISSUE TITLE
[Small Bug] Status window shows a single character with no data on webchats

### ISSUE THREAD

**Issue by T60Group** [realrasengan/jbnc#3]
https://irc.dns.live enter a name/pass and connect
status window shows dozens of:
17:21 []
17:21 []
17:22 []
17:22 []
17:23 []
17:23 []
17:24 []
17:24 []
17:25 []
17:25 []
17:26 []
17:26 []
17:27 []
17:27 []

**Comment by realrasengan** [comment]
This has been fixed! Thank you!
